basename: "ubuntuvm"
replicaCount: 3
running: true

resources:
  requests:
    memory: "1024Mi"
    cpu: "500m"

userDatabase64: "I2Nsb3VkLWNvbmZpZwpwYXNzd29yZDogcGFzc3dkCnNzaF9wd2F1dGg6IFRydWUKY2hwYXNzd2Q6IHsgZXhwaXJlOiBGYWxzZSB9"

dataVolumeTemplates:
  source:
    url: "https://cloud-images.ubuntu.com/focal/20210210/focal-server-cloudimg-amd64.img"
  resources:
    requests:
      storage: 4Gi

ssh:
  publicKey: SSH_PUBLIC_KEY

